### ISSUE TITLE
Is there any public list of systems which pass ACS?

### ISSUE THREAD

**Issue by hrw** [ARM-software/sbsa-acs#101]
I start to wonder are there systems which pass SBSA ACS at all. Especially for level 4 and above.

Tried to run it on several servers from different vendors and it usually crash sooner or later forcing me to reboot machine.

I would like to compare results from SBSA reference platform in QEMU with something physical but looks like there is no such thing.

**Comment by edhay** [comment]
Hi Marcin,

    We have the list of supporters in developer.arm.com
Please check the link: https://developer.arm.com/architectures/system-architectures/arm-systemready/sr

SystemReady SR2.0 certified servers map to SBSA Level 4 and above.

--Enterprise ACS Support
