### ISSUE TITLE
PCIE test 055 checks ATS support on RP

### ISSUE THREAD

**Issue by Jingshan-cwm** [ARM-software/sbsa-acs#111]
Hi 
In PCIE test 055, the test is on RP type, but it checks the ATS capability, In my understanding, most of the time, ATS do exist on device which has ATC, does RP also needs ATS capability on it?
Many thanks,

      bdf = bdf_tbl_ptr->device[tbl_index].bdf;
      dp_type = val_pcie_device_port_type(bdf);

      /* Check entry is RP */
      if (dp_type == RP)
      {
          /* Check If RP supports P2P with other RP's. */
          if (val_pcie_dev_p2p_support(bdf))
              continue;

          /* It ATS Not supported, Skip the BDF. */
          if (val_pcie_find_capability(bdf, PCIE_ECAP, ECID_ATS, &cap_base) != PCIE_SUCCESS) {
              continue;
          }

**Comment by gowthamsiddarthd** [comment]
Hi @Jingshan-cwm,

PCIe test_p055 checks for the rule 
"If the root port supports Address Translation services and peer-to-peer traffic with other root ports, then
it must support ACS direct translated P2P"
 
ATS capability must be supported on the device which has ATC, only if the device is RCiEP or iEP. For Root Port, ATS capability may or may not be supported.
 
So, the test logic checks
1.	For all Root Port present in the system, if the RP supports P2P with other RP's
2.	Check if Address Translation Service(ATS) is supported.
         a. If No, then check for the other RPs
         b. If Yes, then continue
3.	Read the ACS Capability register and extract ACS directed translated P2P bit.
4.	Check if ACS directed translated P2P bit is 1b
 
Regards,
Gowtham
