### ISSUE TITLE
022 Check for pointer signing 

### ISSUE THREAD

**Issue by tingwanyang** [ARM-software/sbsa-acs#118]
https://github.com/ARM-software/sbsa-acs/blob/a8b46b94b69878247d54823f4dc3713a19b0377e/test_pool/pe/test_c022.c#L29

When running sbsa pe c022_entry item, it is failed. 
This case check ID_AA64ISAR1_EL1 register, sbsa testcase check APA, bits [7:4] must be value 0x1,
but armv8 spec says it maybe other value according to armv8 version. Could you give me some help?

**In our system,  ID_AA64ISAR1_EL1.APA[7:4] is 0b0101.**
specs(named DDI0487F_b_armv8_arm.pdf and page 3239) says that From Armv8.6, the permitted 
values are 0b0011, 0b0100, and 0b0101.

this is specs picture.
![image](https://user-images.githubusercontent.com/74529631/105015845-ed620280-5a7c-11eb-8237-58ceaad26a90.png)
![image](https://user-images.githubusercontent.com/74529631/105015920-05398680-5a7d-11eb-8f02-afaa13179612.png)

**Comment by gowthamsiddarthd** [comment]
Hi Tingwan,

Thank you for reporting this.
The below tests are from the SBSA specification scenario
1.	For Level 4
If PEs implement Armv8.3 pointer signing, the PEs must provide the standard algorithm defined by the Arm architecture [3], identified by ID_AA64ISAR1_EL1[7:4]==0001.
 
2.	For Level 5 and above
All PEs must implement pointer signing using the standard algorithm defined by the Arm architecture [3], as indicated by ID_AA64ISAR1_EL1[7:4]==0001.
 
Yes, you are right. The SBSA Specification and test need an update with the updated register description according to Arm ARM. We will be updating the test in the next ACS release based on the update of the SBSA specification.

The proposed errata for SBSA spec is this – 
All PEs must implement pointer signing using the standard algorithm defined by the Arm architecture [3], as indicated by ID_AA64ISAR1_EL1.APA having a non-zero value.

Regards,
Gowtham

**Comment by rajatgoyal47** [comment]
Hi @tingwanyang,

Fix for this issue has been merged as part of #127.
test_c022 is updated to check for non-zero value of ID_AA64ISAR1_EL1[7:4].

Regards,
Rajat
