### ISSUE TITLE
606 Non secure Access to Secure addr

### ISSUE THREAD

**Issue by tingwanyang** [ARM-software/sbsa-acs#120]
https://github.com/ARM-software/sbsa-acs/blob/master/test_pool/peripherals/test_m002.c

when running this case, it seems make stack destroyed, 
the value of the local variable named 'i' is destroyed.

As we see in the fellowing picture, sorry for uart issue, every char print two times.
'for' clause loop variable named 'i' has been destroyed, it is always value 0x1, 
it can not break the 'for' clause.

actually local variable named 'i' should run instruction 'i++', for(i = 0 ; i < 4 ; i++) clause 
make 'i' break 'for' clause. so it seems make stack destroyed.

![image](https://user-images.githubusercontent.com/74529631/104985012-f0dc9600-5a4a-11eb-863e-f17d1ad4182d.png)

[606 Non secure Access to Secure addr.txt](https://github.com/ARM-software/sbsa-acs/files/5833481/606.Non.secure.Access.to.Secure.addr.txt)

**Comment by gowthamsiddarthd** [comment]
Hi @tingwanyang,

We have removed this test from the ACS repository as secure side rules are optional in the spec and this is not required for SystemReady.
This Github Pull Request has the change and will be merged soon. https://github.com/ARM-software/sbsa-acs/pull/125

Regards,
Gowtham

**Comment by rajatgoyal47** [comment]
Hi @tingwanyang,

We have removed this test from the ACS repository as secure side rules are optional in the spec and this is not required for SystemReady.
Closing this issue as this change has been merged as part of #125 

Regards,
Rajat
