### ISSUE TITLE
902 Check System Genric Counter

### ISSUE THREAD

**Issue by tingwanyang** [ARM-software/sbsa-acs#121]
cntcvl register write and read do not comply with the fellowing spec.

according to specs named 'coresight_soc600_technical_reference_manual_100806_0302_00_en.pdf' and page 760.

it says that To change the current timestamp value, write the lower 32 bits of the new value to this register before
writing the upper 32 bits to CNTCVU. The timestamp value is not changed until the CNTCVU register is written to.

this is code link.
https://github.com/ARM-software/sbsa-acs/blob/a8b46b94b69878247d54823f4dc3713a19b0377e/platform/secure_sw/arm-tf/sbsa_avs_main.c#L116

this is specs picture.
![image](https://user-images.githubusercontent.com/74529631/104987896-af031e00-5a51-11eb-8c85-45de810301ec.png)

this is log.(sorry for uart issue, every char print two times.)
[ 902 Check System Genric Counter.txt](https://github.com/ARM-software/sbsa-acs/files/5833673/902.Check.System.Genric.Counter.txt)

**Comment by gowthamsiddarthd** [comment]
Hi @tingwanyang,

The write to CNTCVL does not comply with the spec 'coresight_soc600_technical_reference_manual_100806_0302_00_en.pdf'.
We have removed this test from the ACS repository as secure side rules are optional in the spec and this is not required for SystemReady.
This Github Pull Request has the change and will be merged soon. https://github.com/ARM-software/sbsa-acs/pull/125

Regards,
Gowtham

**Comment by rajatgoyal47** [comment]
Hi @tingwanyang,

We have removed this test from the ACS repository as secure side rules are optional in the spec and this is not required for SystemReady.
Closing this issue as this change has been merged as part of #125 

Regards,
Rajat
