### ISSUE TITLE
Questions on the purpose of peripheral device needed in EXERCISER test 004

### ISSUE THREAD

**Issue by Jingshan-cwm** [ARM-software/sbsa-acs#130]
Hi 
As far as i know, EXERCISER test aimed to do pre-silicon verification, and EXERCISER model will generate PCIE request, why peripheral device needed by test, is there any special reason or limitation that exerciser can not cover?

Questions on the purpose of peripheral device needed in EXERCISER test 004

  uint32_t count = val_peripheral_get_info (NUM_ALL, 0);
  if(!count) {
     val_set_status (index, RESULT_SKIP(g_sbsa_level, TEST_NUM, 3));
     return;
  }

Many thanks

**Comment by gowthamsiddarthd** [comment]
Hi @Jingshan-cwm,

Thank you for pointing this. The mentioned piece of code is not required for the exerciser test.
This has been removed as part of the PR: https://github.com/ARM-software/sbsa-acs/pull/131

Regards,
Gowtham
