### ISSUE TITLE
Drop levels below 3

### ISSUE THREAD

**Issue by hrw** [ARM-software/sbsa-acs#141]
Levels 0, 1, 2 were deprecated with SBSA v5.0 in May 2018.

Maybe it is time to drop support for running lower levels in sbsa-acs? There are several places with checks for lower levels in code.

**Comment by gowthamsiddarthd** [comment]
Hi @hrw,

I've looked into this problem and it seems that the ACS code needs to be updated. Thank you for taking the time to share this and also providing a solution for the same. https://github.com/ARM-software/sbsa-acs/pull/148

Once the code review is complete, the changes will be merged in the master branch.

Regards,
Gowtham
Enterprise ACS support
