### ISSUE TITLE
file permissions are random

### ISSUE THREAD

**Issue by hrw** [ARM-software/sbsa-acs#151]
Files in repository should not have executable bit set.

It is annoyance as executable files are displayed in other way in IDE I am using.

**Comment by gowthamsiddarthd** [comment]
Hi @hrw,

Thank you for this suggestion. The changes have been approved and upstreamed as part of the PR: https://github.com/ARM-software/sbsa-acs/pull/152

Regards,
Gowtham
Enterprise ACS Support
