### ISSUE TITLE
sbsa_acs: Unknown symbol pal_pcie_get_rp_transaction_frwd_support

### ISSUE THREAD

**Issue by bcran** [ARM-software/sbsa-acs#163]
When running the Linux portion of the Enterprise ACS, I'm seeing the error:

[   28.102559] sbsa_acs: Unknown symbol pal_pcie_get_rp_transaction_frwd_support (err 0)
insmod: ERROR: could not insert module /lib/modules/4.18.0-luv/extra/sbsa_acs.ko: Unknown symbol in module

**Comment by rajatgoyal47** [comment]
Hi Rebecca,

Thank you for reporting the issue.
This has been fixed as part of [this commit](https://gitlab.arm.com/linux-arm/linux-acs/-/merge_requests/3) in Gitlab linux-acs repo.

Thanks,
Rajat - ACS team
