### ISSUE TITLE
test issue for test_t007 in timer_wd 

### ISSUE THREAD

**Issue by hensonwang** [ARM-software/sbsa-acs#166]
when timer_num larger than zero, test code will check some register value in cnt_base_n.  The below code is work abnormal:
data = val_mmio_read(cnt_base_n + 0xFD0);
      if ((data == 0x0) || ((data & 0xFFFF) == 0xFFFF)) {
          val_print(AVS_PRINT_ERR, "\n      Unexpected value for CNTBaseN.CounterID %x  ", data);
          val_set_status(index, RESULT_FAIL(g_sbsa_level, TEST_NUM, 0x8));
          return;
      }

based on the description in ARM DDI0487E spec, “If the implementation of the Counter ID registers requires an architecture version, the value for this version of the Arm Generic Timer is version 0”. Why the code should return fail when the data is equal 0? which CounterID value is correct for this test?

**Comment by prasanth-pulla** [comment]
Thanks for reporting this. We have removed the ID check. Fixed in this checkin: 48563e28c3a0f22e45eb1023649310b17744bddb.
This will be picked up in the next release v3.1 which is planned in September.
