### ISSUE TITLE
Does the SBSA requires the UEFI to support multiple Cores/Dies?

### ISSUE THREAD

**Issue by xuesong-lldd** [ARM-software/sbsa-acs#173]
We found that the SBSA will iterate all the interrupt controller structures within the MADT, does that mean the SBSA has a requirement for the underlying UEFI to support all the cores/dies in the system in which the SBSA is running?

**Comment by prasanth-pulla** [comment]
This is only information gathering. UEFI is not expected to support or bring up all cores. Standard UEFI boot for single core is fine.

**Comment by xuesong-lldd** [comment]
> This is only information gathering. UEFI is not expected to support or bring up all cores. Standard UEFI boot for single core is fine.

OK, thanks for the confirm, understood...!
