### ISSUE TITLE
Generating HVP testplans and coverage?

### ISSUE THREAD

**Issue by MikeMiller567** [ARM-software/sbsa-acs#175]
My team is using Synopsys Verification Planner for tracking progress and I would like to use it to plan/track running each of the sbsa tests as they run/pass in my baremetal environment.

I was wondering if anyone had already done something (like a script or something) to create the .hvp plan file and extract/record coverage.

**Comment by gowthamsiddarthd** [comment]
Hi @MikeMiller567,

Currently, we do not have any support to extract or measure the coverage. 
Please contact Synopsys representative for support on this.
	
Regards,
Gowtham

**Comment by MikeMiller567** [comment]
Thanks for getting back to me @gowthamsiddarthd

I'll put together a python program to scrape the data out of the source code and produce the tracking data I need.
