### ISSUE TITLE
SPE requires SVE?

### ISSUE THREAD

**Issue by hrw** [ARM-software/sbsa-acs#187]
Test pe/18 prints "check for SPE" and then checks for SVE and quits it is not present.

I thought that SPE was done before SVE was added to the architecture.

**Comment by prasanth-pulla** [comment]
>>> This is from Arm Arm. Says nothing about SVE.
correct. The ACS is written for SBSA spec. And SBSA spec has this rule.

On the wording of the test summary. It is expected that the statement in the Specification is the accurate and complete statement. The summary a test prints is by no means a complete indication of the functionality. 

The expectation is that - if a deeper understanding of the check is required, the specification will be referred to.

However, having said that, we will consider if the summary can bring out this dependency.
