### ISSUE TITLE
Wrong offsets of PCIe Capability registers

### ISSUE THREAD

**Issue by sunnywang-arm** [ARM-software/sbsa-acs#208]
Similar issue to https://github.com/ARM-software/bsa-acs/pull/10/files  

https://github.com/ARM-software/sbsa-acs/blob/master/platform/pal_baremetal/include/pal_common_support.h#L115

**Comment by gowthamsiddarthd** [comment]
Hi @sunnywang-arm,

Thank you for reporting this. This has been fixed in the PR: https://github.com/ARM-software/sbsa-acs/pull/209

Regards,
Gowtham
