### ISSUE TITLE
SMMU_V3 test forever loop

### ISSUE THREAD

**Issue by ndhillonm** [ARM-software/sbsa-acs#214]
In smmu_v3.c file for testing SMMU, the below function can get stuck in a loop because 'timeout' is not getting decremented in 'while' loop.
Please add a 'timeout--' statement somewhere in 'while' loop.

static void smmu_cmdq_poll_until_consumed(smmu_dev_t *smmu)
{
    uint32_t timeout = SMMU_CMDQ_POLL_TIMEOUT;
    smmu_cmd_queue_t *cmdq = &smmu->cmdq;
    smmu_queue_t queue = {
                .log2nent = smmu->cmdq.queue.log2nent,
                .prod = val_mmio_read((uint64_t)smmu->cmdq.prod_reg),
                .cons = val_mmio_read((uint64_t)smmu->cmdq.cons_reg)
            };

    while (timeout > 0) {
        if (smmu_queue_empty(&queue))
            break;
        queue.cons = val_mmio_read((uint64_t)cmdq->cons_reg);
    }

    if (!timeout) {
        val_print(AVS_PRINT_ERR, "\n      CMDQ poll timeout at 0x%08x", queue.prod);
        val_print(AVS_PRINT_ERR, "\n      prod_reg = 0x%08x,", val_mmio_read((uint64_t)smmu->cmdq.prod_reg));
        val_print(AVS_PRINT_ERR, "\n      cons_reg = 0x%08x", val_mmio_read((uint64_t)smmu->cmdq.cons_reg));
        val_print(AVS_PRINT_ERR, "\n      gerror   = 0x%08x     ", val_mmio_read(smmu->base + SMMU_GERROR_OFFSET));
    }
}

**Comment by chetan-rathore** [comment]
Hi @ndhillonm,

The timeout changes along with some other changes are merged as part of #215

Thanks,
ACS team
