### ISSUE TITLE
Issue with fast system timer frequency

### ISSUE THREAD

**Issue by jbrasen** [ARM-software/sbsa-acs#229]
Found what appears to be an issue with a couple ACS UEFI tests.

1. https://github.com/ARM-software/sbsa-acs/blob/master/test_pool/timer_wd/test_t001.c#L36 limits CNTFREQ to be between 10Mhz and 400Mhz which is no longer a requirement in the SBSA specification (replaced by 10 year rollover).
2. With this timer frequency the large timeout used in the watchdog test (https://github.com/ARM-software/sbsa-acs/blob/master/test_pool/power_wakeup/test_u001.c#L122) does not seem to be longer than the watchdog timer.

**Comment by Jiss-Jose** [comment]
Hi @jbrasen ,

This issue is fixed with  pull request #230 .

Thanks
ACS Team
