### ISSUE TITLE
PSCI conduit is assumed to be SMC

### ISSUE THREAD

**Issue by darkwood101** [ARM-software/sbsa-acs#263]
Per the SMCCC and PSCI specifications, the conduit for performing PSCI calls is platform-dependent and it can either be SMC (Secure Monitor Call) or HVC (Hypervisor Call).

The current SBSA implementation assumes that the conduit is SMC. This causes PSCI calls to fail on some platforms. Instead, the conduit for PSCI calls should be retrieved from the ARM_BOOT_ARCH field of the FADT ACPI table.

**Comment by chetan-rathore** [comment]
Hi @darkwood101, 

The PR is merged in main branch.

Thanks,
ACS team

**Comment by darkwood101** [comment]
Thanks!
