### ISSUE TITLE
SBSA Linux Test 407 should not check the RCiEP that doesn't support interrupt 

### ISSUE THREAD

**Issue by sunnywang-arm** [ARM-software/sbsa-acs#278]
Similar issue to https://github.com/ARM-software/sbsa-acs/issues/270

**Comment by chetan-rathore** [comment]
Hi @sunnywang-arm, 

With the SBSA v6.1.0 updates, test 407 MSI, MSI-X check functionality will be covered by
* SBSA pcie test 41 (https://github.com/ARM-software/sbsa-acs/blob/master/test_pool/pcie/test_p041.c)  for RCiEP and iEP devices.
* BSA pcie test 36 (https://github.com/ARM-software/bsa-acs/blob/main/test_pool/pcie/operating_system/test_os_p039.c)  for non integrated endpoints. 

Thanks,
ACS team
