### ISSUE TITLE
SBSA test "1301 : Check peripherals addr 64Kb apart" issues

### ISSUE THREAD

**Issue by sunnywang-arm** [ARM-software/sbsa-acs#293]
- Sujana found that the SBSA test 1301 hasn't checked for all BAR registers, which might cause failure.   
- We need to print out more messages to know which peripheral has been checked and caused the failure. 
- Moreover, after the test find the problematic peripheral, it should continue checking other peripherals rather than just stopping testing

**Comment by chetan-rathore** [comment]
Hi @sunnywang-arm,

ACS team is working on the changes and will raise the PR soon.

Thanks,
ACS team

**Comment by chetan-rathore** [comment]
Hi @sunnywang-arm, 

The changes are merged in mainline.

Thanks,
ACS team
