### ISSUE TITLE
S_L4PCI_2 is tested only on SBSA level 6+

### ISSUE THREAD

**Issue by hrw** [ARM-software/sbsa-acs#297]
SBSA Level 4 checklist has two PCIe entries: S_L4PCI_1 and S_L4PCI_2. Second one is tested in test 462:

```
 462 : Check EA Capability               
       START  
       S_L4PCI_2
                                  : Result:  PASS 
       END  
```

But PCIe tests are run only for SBSA level 6 and above...

**Comment by chetan-rathore** [comment]
Hi @hrw,

The changes will involve some infra changes in ACS code, we will keep you updated about the issue progress.

Thanks,
ACS team

**Comment by chetan-rathore** [comment]
Hi @hrw,

Changes for the issue are merged. 
Test id of test is changed to reflect it as peripheral test, but as the test uses PCIe framework it will run as part of pcie tests.

Thanks,
ACS team
