### ISSUE TITLE
PE Test015-"Check MPAM PE Requirements" Need judg Nerverse N2  version.

### ISSUE THREAD

**Issue by JackWeihuadi** [ARM-software/sbsa-acs#302]
For Armv8.5 MAX_PMG=1 is okay. 
https://services.arm.com/support/s/case/5004L00000TY1lB

**Comment by chetan-rathore** [comment]
Hi @JackWeihuadi,

Code changes are expected to be upstream by this week.

Thanks,
ACS team

**Comment by chetan-rathore** [comment]
Hi @JackWeihuadi,

The fix is merged.
