### ISSUE TITLE
Memory corruption inside sbsa main function.

### ISSUE THREAD

**Issue by pttuan** [ARM-software/sbsa-acs#31]
In SbsaAvs.h
#define GIC_INFO_TBL_SZ        2048
#define PCIE_INFO_TBL_SZ       64

Those sizes are too small for some systems with a lot of CPUs and PCIE MCFG entries so after allocating memory and fill up the info read from ACPI table, the memory is corrupted.

**Comment by prasanth-pulla** [comment]
The sizes have been updated to support 256 PEs.
the commit ID is 75a74908e5168de6ae1b2f1faf89b8587cee6570

We will look at implementing a dynamic memory allocation scheme in the upcoming major release which is planned for Q1 of 2018.
