### ISSUE TITLE
Test 861 uses S_PCI_02 tag which is not in SBSA spec

### ISSUE THREAD

**Issue by hrw** [ARM-software/sbsa-acs#317]
Test 861 lists S_PCI_02 tag:

```
 861 : Check RootPort P&NP Memory Access 
       S_PCI_02
       Checkpoint --  1                  : Result:  SKIPPED 
```

But SBSA 7.1 (DEN0029H) spec does not use S_PCI_* tags. It has S_PCIe_* tags.

S_PCIe_02 tag says:

> The Root Port must support the following:
> • 1B and 2B read from Prefetchable and Non-prefetchable address spaces.
> • 1B and 2B write to Prefetchable and Non-prefetchable address spaces.
> This must hold true for accesses to downstream functions as well as to the Root Port itself. This must hold true even when the read or write address is not DW (4 Byte) aligned.

Please update ACS.

**Comment by chetan-rathore** [comment]
Hi @hrw, 

Changes are merged for the issue.

Thanks,
ACS team

**Comment by hrw** [comment]
Now test 601 uses wrong tag:

```
      *** Starting PCIe tests ***
 601 : Check EA Capability
       START
       BDF - 0x100
       BDF - 0x300
       BDF - 0x400
       BDF - 0x500
       BDF - 0x600
       BDF - 0x10000
       BDF - 0x20000
       BDF - 0x30000
       BDF - 0x40000
       S_L4PCI_2
                                  : Result:  PASS
       END


      All PCIe tests passed.
```

**Comment by hrw** [comment]
Sorry, was occupied with some stuff.

Also "we do everything in one commit" policy you use make finding things harder.
