### ISSUE TITLE
Test 16  (Check MPAM LLC Requirements) should check MPAM before PPTT LLC        

### ISSUE THREAD

**Issue by sunnywang-arm** [ARM-software/sbsa-acs#349]
On Test 16 in the SBSA: 16: Check MPAM LLC Requirements we see the following description:

![image](https://github.com/ARM-software/sbsa-acs/assets/81214085/8f2f5765-258a-464c-923f-a885d06e6bef)

In the code however (https://github.com/ARM-software/sbsa-acs/blob/10d30f6496e40607a0844688b881e480a9bc0b3f/test_pool/pe/operating_system/test_c016.c#L52), it looks like the PPTT LLC (step 5) is checked before the MPAM feature is checked (the test entry condition).  This can lead to an error if MPAM is not supported.

**Comment by chetan-rathore** [comment]
Hello @sunnywang-arm,

Partner PR request  #350 for the issue is merged.

Thanks,
ACS team

**Comment by chetan-rathore** [comment]
Hi @sunnywang-arm,

Thanks for reporting the issue. Closing it as changes are merged. 

Thanks,
ACS team
