### ISSUE TITLE
PE test 16 (rule S_MPAM_PE) could be more verbose on failure

### ISSUE THREAD

**Issue by paulzzy** [ARM-software/sbsa-acs#384]
https://github.com/ARM-software/sbsa-acs/blob/3b6e10a812da5e311f3ef8541233088691d3d3a7/test_pool/pe/operating_system/test_c016.c#L68

In PE test 16 (rule S_MPAM_PE), when it fails due to a zero MSC node count, it does not print that it failed because MSC count is zero. Every other sub-test prints the cause of failure, except for the MSC count sub-test. It would be helpful to print that the MSC count is zero when this sub-test fails, so verbose debugging doesn't have to be enabled to identify the cause.

Here's a fork that illustrates a possible solution:

https://github.com/paulzzy/sbsa-acs/blob/1975e6e581c48e051a15cd1fc892fcd1b45eafec/test_pool/pe/operating_system/test_c016.c#L69

**Comment by chetan-rathore** [comment]
Thanks @paulzzy for the inputs.

We can make the required changes as suggested by you, but would appreciate in case you want to directly contribute by raising PR.

Thanks,
ACS team
