### ISSUE TITLE
ACS Linux failed to mount result partition 

### ISSUE THREAD

**Issue by foxmmmm** [ARM-software/sbsa-acs#429]
If a system has many BOOT-like label partitions, the "BLOCK_DEVICE_NAME=$(blkid | grep "BOOT" | awk -F: '{print $1}')" cmd will return many drive partition strings, then fail to execute "mount $BLOCK_DEVICE_NAME /mnt":
BusyBox v1.35.0 (2023-09-29 16:18:45 UTC) multi-call binary.

Usage: mount [OPTIONS] [-o OPT] DEVICE NODE

Mount a filesystem. Filesystem autodetection requires /proc.

	-a		Mount all filesystems in fstab
	-r		Read-only mount
	-t FSTYPE[,...]	Filesystem type(s)
	-T FILE		Read FILE instead of /etc/fstab
	-O OPT		Mount only filesystems with option OPT (-a only)
-o OPT:
	loop		Ignored (loop devices are autodetected)
	[a]sync		Writes are [a]synchronous
	[no]atime	Disable/enable updates to inode access times
	[no]diratime	Disable/enable atime updates to directories
	[no]relatime	Disable/enable atime updates relative to modification time
	[no]dev		(Dis)allow use of special device files
	[no]exec	(Dis)allow use of executable files
	[no]suid	(Dis)allow set-user-id-root programs
	[r]shared	Convert [recursively] to a shared subtree
	[r]slave	Convert [recursively] to a slave subtree
	[r]private	Convert [recursively] to a private subtree
	[un]bindable	Make mount point [un]able to be bind mounted
	[r]bind		Bind a file or directory [recursively] to another location
	move		Relocate an existing mount point
	remount		Remount a mounted filesystem, changing flags
	ro		Same as -r

There are filesystem-specific -o flags.
Mounted the results partition on device /dev/sda1
/dev/nvme0n1p6
/dev/nvme0n1p5
/dev/nvme0n1p1

# blkid | grep "BOOT"
/dev/sda1: LABEL="BOOT" UUID="23EA-757A"
/dev/nvme0n1p6: LABEL="BOOTBANK2" UUID="582C-4BE0"
/dev/nvme0n1p5: LABEL="BOOTBANK1" UUID="582C-4BE0"
/dev/nvme0n1p1: LABEL="BOOT" UUID="582C-4BE0"

/ # blkid | grep "BOOT" | awk -F: '{print $1}'
/dev/sda1
/dev/nvme0n1p6
/dev/nvme0n1p5
/dev/nvme0n1p1

**Comment by chetan-rathore** [comment]
Hello @foxmmmm,

To handle the scenario where more than one partition is carrying a BOOT** label, we will append _ACS to the BOOT labe
We will upstream the changes by end of this week.

Thanks,
ACS team
