### ISSUE TITLE
Features not supported causes test item to fail

### ISSUE THREAD

**Issue by hysen0523** [ARM-software/sbsa-acs#439]
Test item in BSA "6. Check Cryptographic extensions" failed. The root cause is that bits 7:4, 11:8, 15:12 of ID_AA64ISAR0_EL1 are all zeros. Should this test case be waived? Or, update this test case to get a "skip" result if FEAT_AES/FEAT_SHA1/FEAT_SHA256 not supported? Or other solutions? Thanks a lot.

<img width="599" alt="image" src="https://github.com/ARM-software/sbsa-acs/assets/41116023/43ec0252-9168-4d27-8d56-3df9c952d897">

Additionally, there are other identical failing test cases in BSA or SBSA, should they be waived? Or other solutions?
1. In SBSA "10, Check for pointer signing" failed, because ID_AA64ISAR1_EL1.APA (bit[4:7])=0
2. In SBSA "12, Check for SHA3 and SHA512 support" failed, because ID_AA64ISAR0_EL1.SH3(bit32-35)=0, .SHA2(bit12-15)=0
3. In SBSA "14, Check for nested virtualization" failed, because ID_AA64MMFR2_EL1 bit[24:27]=0

**Comment by chetan-rathore** [comment]
Hi @hysen0523,

The tests mentioned above has recently been updated, Can you confirm if the results are with latest binary or with SR or ES systemready image.
 
Also can you provide information on the SBSA level selected to run the tests.

Thanks,
ACS team

**Comment by chetan-rathore** [comment]
Hello @hysen0523,

You are correct that the rules tested by the mentioned test have dependency on export restrictions.
We will add a user command line parameter to get if export restrictions allowed or not, and test SKIP or FAIL will depend on the flag value.

Thanks,
ACS team
