### ISSUE TITLE
PE Test 16 (Check MPAM LLC Requirements) doesn't support the case where ACPI MAPM's MSCs are PCC based 

### ISSUE THREAD

**Issue by sunnywang-arm** [ARM-software/sbsa-acs#454]
When the MSCs are PCC based, the Base Address field of the MPAM MSC node is the subspace ID of the PCC channel rather than the Base address of the memory-mapped MPAM register space. In this case, we’ll need to get the MPAM register space from the ACPI PCCT table. However, sbsa-acs doesn’t support this case.

**Comment by samerhaj** [comment]
MPAM over "ACPI PCC" is described in [MPAM Firmware-backed (Fb) Profile Specification ](https://developer.arm.com/documentation/den0144/0100/?lang=en )

**Comment by chetan-rathore** [comment]
Hi @samerhaj  and @sunnywang-arm,
 
The MPAM test will need update for the cases when MPAM register space is exposed via PCCT table.
We are working on it and will keep you updated.

Thanks,
ACS team
