### ISSUE TITLE
Add a tag to test 901

### ISSUE THREAD

**Issue by hrw** [ARM-software/sbsa-acs#479]
I am working on updating my [BSA/SBSA checklist](https://marcin.juszkiewicz.com.pl/download/tables/bsa-sbsa.html) and noticed that test 901 does not have any tags attached so it ends with "checks nothing" at table (as tags are indexes there).

Can it get one?

**Comment by rajatgoyal47** [comment]
Hi,

We have updated the test and checklist.

Regards,
ACS Team
