### ISSUE TITLE
test 844 checks for PCI_IN_04 but other way than BSA ACS one

### ISSUE THREAD

**Issue by hrw** [ARM-software/sbsa-acs#481]
Test 844 skips in my system:

```
 844 : Check device under RP in same ECAM    
       START
       No iEP_EP type device found. Skipping test
       PCI_IN_04
       Checkpoint --  1                           : Result:  SKIPPED
       END
```

PCI_IN_04 is also checked in BSA ACS and passes:

```
 803 : All EP/Sw under RP in same ECAM Region
       START
       BDF - 0x100
       BDF - 0x200
       BDF - 0x300
       BDF - 0x400
       BDF - 0x500
       BDF - 0x600
       BDF - 0x700
       BDF - 0x800
       BDF - 0x10000
       BDF - 0x20000
       BDF - 0x40000
       BDF - 0x50000
       BDF - 0x60000
       BDF - 0x80000
       PCI_IN_04
                                       : Result:  PASS
       END
```

Same system. Can those tests be in sync with each other? Or get different tags? Or something?

**Comment by rajatgoyal47** [comment]
Hi Marcin,

The PCIe tests in BSA ACS are run for Rootports, Endpoints, and Switches, but not for integrated devices such as iEP_EP, iEP_RP, and RCiEP. 
For integrated endpoints, the SBSA ACS PCIe tests are applied.

Both tests address the same rule: PCI_IN_04

Regards,
ACS Team
