### ISSUE TITLE
test_mpam003.c is not generic

### ISSUE THREAD

**Issue by ablackham52** [ARM-software/sbsa-acs#482]
test_mpam003.c is not generic enough of a test for testing rules S_L7MP_05, S_L7MP_06 on a baremetal platorm.

The test calls
`                /* perform memory operation */
                val_memcpy(src_buf, dest_buf, BUFFER_SIZE);`
Which according to the documentation copies a source buffer to a destination buffer. The test then assumes this function will perform reads and writes for the entire buffer size. There needs to be better documentation on what type of traffic is expected.
`                /* the monitor must count both read and write bandwidth,
                   hence count must be twice of the buffer size */
                if ((byte_count != 2 * BUFFER_SIZE)) {`

Also, this test expects an exact count on the MBWU which is unrealistic without knowing the implementation details of the platform, its difficult to guarantee that exact buffer will be the only accesses.

This test should be similar to the PMU tests which simply checks that the value is larger for a larger buffer.

**Comment by SrikarJosyula** [comment]
Hi @ablackham52,
 
MPAM test 003 allocates the source and destination buffers on the memory regions of MSC where MBWU monitor can count the transactions. Similar to that of ACPI target, baremetal target also expects the reads from source buffer and the writes into the destination buffer. We can update the val_memcpy documentation in baremetal to explicitly mention the reads and writes traffic.
 
We agree regarding the strict check on monitor counting the exact number of reads and writes. We will relax the check making allowance for implementation nuances.
 
Thanks,
ACS team
