### ISSUE TITLE
Get wrong affix in val_pe_get_mpid

### ISSUE THREAD

**Issue by tphan-ampere** [ARM-software/sbsa-acs#83]
Looks like val_pe_get_mpid is getting wrong affix bits
Patch to fix
diff --git a/val/src/avs_pe_infra.c b/val/src/avs_pe_infra.c
index a2fcd71..34cec9d 100644
--- a/val/src/avs_pe_infra.c
+++ b/val/src/avs_pe_infra.c
@@ -105,7 +105,7 @@ val_pe_get_mpid()
   //
   //return the affx bits
   //
-  data = (((data >> 32) & 0xFF) << 24) | (data & 0xFFFFFF);
+  data = (((data >> 32) & 0xFF) << 32) | (data & 0xFFFFFF);
   return data;

 }

**Comment by edhay** [comment]
Thank you. The above fix is merged in the pull request
https://github.com/ARM-software/sbsa-acs/pull/84
